export interface AnimalsI {
	id: number,
	organization_id: string,
	url: string,
	type: string,
	species: string,
	breeds: object,
	colors: object,
	age: string,
	gender: string,
	size: string,
	coat: string,
	attributes: object,
	environment: object,
	tags: string[],
	name: string,
	description: string,
	organization_animal_id: string,
	photos: object[],
	primary_photo_cropped: object,
	videos: object[],
	status: string,
	status_changed_at: string,
	published_at: string,
	distance: string,
	contact: object,
	_links: object
}